name: CI/CD Next Homelab

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and push Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USER }}/homelab-next-app:latest .
          docker push ${{ secrets.DOCKER_USER }}/homelab-next-app:latest

      - name: Deploy to Homelab
        run: |
          kubectl delete deployment homelab-next-app --ignore-not-found
          kubectl apply -f k8s/deployment.yaml
          kubectl rollout status deployment homelab-next-app
